[package]
name = "vidfx-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
ffmpeg-next = "7.1.0"
image = "0.25.5"
imgfx = { path = "/home/gabriel/code/rust/imgfx-crate/"}
